apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: order-management-service

build:
  artifacts:
    - image: order-management-service
      context: .
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - ./configuration/secrets.yaml
      - ./configuration/deployment.yaml
      - ./configuration/service.yaml
      - ./configuration/database.yaml

portForward:
  - resourceType: service
    resourceName: order-management-postgres
    port: 5432
    localPort: 5432