apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  database_url: postgresql+asyncpg://myuser:mypassword@order-management-postgres:5432/order_management_db
  auth_secret_key: uLz#y49&m9@P3Ks^WdX!2*GnV7b$XrAq